---
- name: Restart iptables
  systemd:
    name: iptables
    state: restarted
  become: true
  notify:
    - restart docker

- name: Restart OpenSSH server
  systemd:
    name: sshd
    state: restarted
  when: archlinux_enable_openssh_server
  become: true
