---
- name: Detect display controllers
  shell: lspci -mnn | grep -E '\[03[0-9]{2}]' | grep -i {{ item }}
  with_items:
    - amd
    - nvidia
  register: display_controllers
  ignore_errors: true

- name: Install mesa (OpenGL implementation)
  pacman:
    name:
      - mesa
      - mesa-demos
      - libva-mesa-driver
      - mesa-vdpau
  become: true

- name: Install AMD display drivers
  pacman:
    name:
      - xf86-video-amdgpu
      - vulkan-radeon
  when: not display_controllers.results[0].failed
  become: true

- name: Install Nvidia display drivers
  pacman:
    name:
      - nvidia
  when: not display_controllers.results[2].failed
  become: true
