---
- name: Install xinit
  pacman:
    name:
      - xorg-xinit
  become: true

- name: Install fonts
  pacman:
    name:
      - adobe-source-code-pro-fonts
      - adobe-source-han-sans-jp-fonts
      - noto-fonts
      - noto-fonts-emoji
      - powerline-fonts
      - ttf-dejavu
      - ttf-droid
      - ttf-inconsolata
      - ttf-liberation
  become: true

- name: Install display configuration tools
  pacman:
    name:
      - arandr
      - lxrandr
  become: true

- name: Install xclip
  pacman:
    name:
      - xclip
  become: true

- name: Install GUI themes
  pacman:
    name:
      - xcursor-premium
  become: true
